[package]
name = "quick-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.8"
indicatif = { version = "0.18", features = ["rayon"] }
rayon = "1.5"
